import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./theme/ThemeContext";


export const metadata: Metadata = {
  title: "Ti Vi Ali",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
        {children}
        </ThemeProvider>
        </body>
    </html>
  );
}
