import type { Metadata } from "next";

import { AuthProvider } from "./dash/components/authprovider/ProvSession";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <>

<AuthProvider>

        {children}

</AuthProvider>


{/* apenas um teste */}


    </>

  );
}
